CREATE TABLE `digest_ab_tests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(200) NOT NULL,
	`status` varchar(20) NOT NULL DEFAULT 'draft',
	`variantAName` varchar(100) DEFAULT 'Variant A',
	`variantASubjectLine` varchar(200),
	`variantASectionOrder` json,
	`variantAIncludeSections` json,
	`variantBName` varchar(100) DEFAULT 'Variant B',
	`variantBSubjectLine` varchar(200),
	`variantBSectionOrder` json,
	`variantBIncludeSections` json,
	`variantASent` int DEFAULT 0,
	`variantAOpened` int DEFAULT 0,
	`variantAClicked` int DEFAULT 0,
	`variantBSent` int DEFAULT 0,
	`variantBOpened` int DEFAULT 0,
	`variantBClicked` int DEFAULT 0,
	`winningVariant` varchar(1),
	`winningReason` text,
	`startedAt` timestamp,
	`completedAt` timestamp,
	`testDuration` int DEFAULT 4,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `digest_ab_tests_id` PRIMARY KEY(`id`)
);
